Repository bullfrogsec/bullfrog, pull requests merged in 2024-07, with the labels that each got.

#37 ci: Set dns-policy to block in build job
  .github/workflows/bullfrog.yml
Labels: ci

#38 ci: Add a newline between steps
  .github/workflows/bullfrog.yml
  .github/workflows/conventional-commit.yml
Labels: ci

#39 fix: Verify Tetragon SHA256 checksum
  action/scripts/install_tetragon.sh
Labels: fix

#41 fix: only allow trusted local dns server
  agent/queue_block_with_dns.nft
Labels: fix

#45 fix: filtering dns server in agent instead of nftables
  .github/workflows/bullfrog.yml
  .vagrant/provision.sh
  agent/main.go
  agent/queue_block_with_dns.nft
  test/input.js
Labels: fix

#46 ci: set release as latest
  .github/workflows/bullfrog.yml
Labels: ci

#47 ci: Run integration tests in a local VM
  .github/workflows/bullfrog.yml
  .vagrant/provision.sh
  Makefile
  action/Makefile
  action/dist/main.js.map
  action/scripts/install_tetragon.sh
  action/src/main.ts
  test/block.env.js
  test/block.sh
  test/make_dns_requests.sh
  test/make_http_requests.sh
Labels: ci

#48 ci: Enforce code style
  .github/workflows/bullfrog.yml
  Makefile
  action/.prettierrc
  action/Makefile
  action/dist/main.js
  action/dist/main.js.map
  action/dist/post.js
  action/dist/post.js.map
  action/eslint.config.js
  action/package-lock.json
  action/package.json
  action/src/main.ts
  action/src/post.ts
  action/src/util.ts
  agent/Makefile
  agent/main.go
Labels: ci

#49 feat: Prefix internal inputs with an underscore
  .github/workflows/bullfrog.yml
  action.yml
  action/dist/main.js
  action/dist/main.js.map
  action/dist/post.js
  action/dist/post.js.map
  action/src/inputs.ts
  test/block.env.js
  test/input.js
Labels: feat

#51 ci: Set pre-release and release to block mode
  .github/workflows/bullfrog.yml
Labels: ci

#52 fix: Close file descriptors
  action/dist/main.js
  action/dist/main.js.map
  action/scripts/install_tetragon.sh
  action/src/main.ts
  test/block.sh
Labels: fix

#54 ci: Add tests for post step
  test/block.sh
  test/make_http_requests.sh
Labels: ci

#64 chore: pinning all bullfrog actions
  .github/workflows/bullfrog.yml
  .github/workflows/conventional-commit.yml
  README.md
Labels: chore

#65 docs: pin action commit in usage examples
  README.md
Labels: docs

#66 fix: remove any connections before the agent is ready
  action/dist/main.js.map
  action/dist/post.js
  action/dist/post.js.map
  action/src/post.ts
  action/src/util.ts
  agent/agent.go
Labels: fix

#68 ci: skip build on markdown updates
  .github/workflows/bullfrog.yml
Labels: ci

#70 chore: bumping bullfrog in docs and workflows
  .github/workflows/bullfrog.yml
  .github/workflows/conventional-commit.yml
  README.md
Labels: chore

#71 feat: Add `enable-sudo` input
  .github/workflows/bullfrog.yml
  Makefile
  README.md
  action.yml
  action/Makefile
  action/dist/main.js
  action/dist/main.js.map
  action/dist/post.js
  action/dist/post.js.map
  action/src/inputs.ts
  action/src/main.ts
  agent/Makefile
  agent/agent.go
  agent/agent_test.go
  agent/main.go
  test/block.env.js
  test/block.sh
  test/run_sudo_commands.sh
Labels: feat

#73 docs: Update branding
  action.yml
Labels: docs

#79 feat: Verify agent checksum
  .github/workflows/bullfrog.yml
  Makefile
  action.yml
  action/Makefile
  action/dist/main.js
  action/dist/main.js.map
  action/dist/post.js
  action/dist/post.js.map
  action/scripts/download_agent.sh
  action/src/inputs.ts
  action/src/main.ts
  agent/Dockerfile
  agent/Makefile
  agent/agent.sha256
  test/block.env.js
  test/input.js
Labels: feat
